enum 💾Key {
    static let hideDate: String = "hideDate"
    static let showYear: String = "showYear"
    static let hideWeekday: String = "hideWeekday"
    static let showSecond: String = "showSecond"
    static let fontSize: String = "fontSize"
    static let fontWeight: String = "fontWeight"
    static let fontDesign: String = "fontDesign"
    static let textColor: String = "textColor"
    static let padding: String = "padding"
    static let opacity: String = "opacity"
    static let hideBackground: String = "hideBackground"
    static let angle: String = "angle"
    static let animation: String = "animation"
    static let tapCountForOpenSettingButton: String = "tapCountForSettingButton"
    static let showBattery: String = "showBattery"
    static let showBatteryNumber: String = "showBatteryNumber"
    static let customizeDateTimeLayout: String = "customizeDateTimeLayout"
    static let datePosition: String = "datePosition"
    static let spaceBetweenDateAndTime: String = "spaceBetweenDateAndTime"
    static let batteryPosition: String = "batteryPosition"
    static let spaceBetweenClockAndBattery: String = "spaceBetweenClockAndBattery"
    
    static let hideDateOnWidget: String = "hideDateOnWidget"
    static let showYearOnWidget: String = "showYearOnWidget"
    static let hideWeekdayOnWidget: String = "hideWeekdayOnWidget"
    static let showSecondOnWidget: String = "showSecondOnWidget"
    static let fontSizeOnWidget: String = "fontSizeOnWidget"
    static let fontWeightOnWidget: String = "fontWeightOnWidget"
    static let fontDesignOnWidget: String = "fontDesignOnWidget"
    static let opacityOnWidget: String = "opacityOnWidget"
    static let spaceBetweenLinesOnWidget: String = "spaceBetweenLinesOnWidget"
    static let alignmentOnWidget: String = "alignmentOnWidget"
    static let showBatteryOnWidget: String = "showBatteryOnWidget"
    static let batteryLabelStyleOnWidget: String = "batteryLabelStyleOnWidget"
}
